name: Code Quality Check

on: [push, pull_request, issues]

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      
      - uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: yarn

      - name: Lint Check
        run: yarn lint

      - name: Prettier Check
        run: yarn format
    
      - name: Build Workspace
        run: yarn build